# Generated by Django 3.0.3 on 2021-04-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='image',
            field=models.ImageField(help_text='280x475px', upload_to='', verbose_name='Изображение товара'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата заказа')),
                ('time_order', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время заказа')),
                ('price_order', models.TextField(blank=True, null=True, verbose_name='Стоимость заказа')),
                ('payment_method', models.TextField(blank=True, null=True, verbose_name='Способ оплаты')),
                ('way_of_getting', models.TextField(blank=True, null=True, verbose_name='Способ получения')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Candle')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-date_order', '-time_order'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('discount', models.FloatField(verbose_name='Скидка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Candle')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
